version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: filterproject
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: