/*

import com.orhanararat.model.IPAddressRange

rule "Default Allow"
    salience -100
when
    $ip : IPAddress()
then
    $ip.setAllowed(true);
end

// Localhost'a her zaman izin ver
rule "Allow Localhost"
    salience 100
when
    $ip : IPAddress(address == "127.0.0.1" || address == "0:0:0:0:0:0:0:1")
then
    $ip.setAllowed(true);
end

// Örnek: Belirli bir IP aralığını engelle
rule "Block Specific Range"
when
    $ip : IPAddress(address.startsWith("192.168.0."))
then
    $ip.setAllowed(false);
end*/
